[server]
maxUploadSize = 400

[browser]
gatherUsageStats = false

[theme]
base="light"
primaryColor="#17191c"
backgroundColor="#f7f7f8"
secondaryBackgroundColor="#ffffff"
textColor="#17191c"
font="sans serif"
